import type { ProjectRole } from "../types";

export type AgentId =
  | "research-intake" | "outlet-matching" | "search-planning" | "literature-retrieval"
  | "screening" | "evidence-extraction" | "literature-synthesis" | "contradiction-detection"
  | "research-gap" | "question-hypothesis" | "methodology-design" | "analysis-planning"
  | "results-interpretation-writing" | "section-writer" | "peer-review" | "compliance"
  | "integrity-review" | "manuscript-editor" | "export";

export type AgentModelTier = "Deterministic" | "Language—Standard" | "Language—Advanced";

export interface AgentContract {
  id: AgentId;
  purpose: string;
  allowedInputArtifacts: readonly string[];
  allowedTools: readonly string[];
  outputSchema: { id: string; version: string; requiredFields: readonly string[] };
  modelTier: AgentModelTier;
  requiredWorkflowStates: readonly string[];
  humanReviewRequirement: "Required before persistence/use" | "Required before downstream use" | "Deterministic—researcher review required for disposition";
  nextStates: readonly string[];
  prohibitedBehavior: readonly string[];
  permissions: {
    serverOnly: true;
    frontendInvocation: "Allowed" | "Denied";
    roles: readonly ProjectRole[];
  };
}

const WRITERS: readonly ProjectRole[] = ["Owner", "Corresponding Author", "Co-author", "Supervisor", "Statistician"];
const REVIEWERS: readonly ProjectRole[] = [...WRITERS, "Reviewer"];
const NEVER = ["Fabricate evidence, citations, data, statistics, approvals, or provenance", "Self-approve output or bypass human review", "Use artifacts or tools outside this contract"] as const;
const schema = (id: string, requiredFields: string[]) => ({ id, version: "1.0", requiredFields: Object.freeze(requiredFields) });
const contract = (value: AgentContract): AgentContract => Object.freeze({
  ...value,
  allowedInputArtifacts: Object.freeze([...value.allowedInputArtifacts]), allowedTools: Object.freeze([...value.allowedTools]),
  requiredWorkflowStates: Object.freeze([...value.requiredWorkflowStates]), nextStates: Object.freeze([...value.nextStates]),
  prohibitedBehavior: Object.freeze([...value.prohibitedBehavior]), permissions: Object.freeze({ ...value.permissions, roles: Object.freeze([...value.permissions.roles]) }),
  outputSchema: Object.freeze({ ...value.outputSchema, requiredFields: Object.freeze([...value.outputSchema.requiredFields]) }),
});

const definitions: AgentContract[] = [
  contract({ id: "research-intake", purpose: "Classify researcher-supplied project context and identify missing intake information.", allowedInputArtifacts: ["researchDescription", "statedClassification"], allowedTools: ["structured-language-model"], outputSchema: schema("AgentSuggestionEnvelope", ["summary", "proposals", "missingInformationFlags", "evidenceIds"]), modelTier: "Language—Standard", requiredWorkflowStates: ["Project Created"], humanReviewRequirement: "Required before downstream use", nextStates: ["Intake Suggested", "Intake Researcher Confirmed"], prohibitedBehavior: [...NEVER, "Default to a clinical or crossover study type"], permissions: { serverOnly: true, frontendInvocation: "Allowed", roles: WRITERS } }),
  contract({ id: "outlet-matching", purpose: "Rank only supplied verified outlet records against researcher-supplied manuscript context.", allowedInputArtifacts: ["manuscriptProfile", "verifiedOutletCatalogue", "outletConstraints"], allowedTools: ["outlet-intelligence-service", "deterministic-matcher"], outputSchema: schema("OutletMatchingProposal", ["recommendations", "missingInformation"]), modelTier: "Deterministic", requiredWorkflowStates: ["Manuscript Profile Available"], humanReviewRequirement: "Required before downstream use", nextStates: ["Outlet Suggestions Available", "Outlet Researcher Selected"], prohibitedBehavior: [...NEVER, "Invent outlet metrics, indexing, requirements, or acceptance probability"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "search-planning", purpose: "Propose reproducible provider-specific literature search plans.", allowedInputArtifacts: ["approvedResearchQuestion", "searchConcepts", "searchConstraints"], allowedTools: ["search-query-compiler"], outputSchema: schema("SearchPlanProposal", ["concepts", "providerSyntax", "filters"]), modelTier: "Language—Standard", requiredWorkflowStates: ["Research Question Approved"], humanReviewRequirement: "Required before downstream use", nextStates: ["Search Plan Suggested", "Search Plan Approved"], prohibitedBehavior: [...NEVER, "Claim a search was executed"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "literature-retrieval", purpose: "Execute an approved search plan against named real providers.", allowedInputArtifacts: ["approvedSearchPlan"], allowedTools: ["Crossref", "OpenAlex", "PubMed", "Europe PMC", "arXiv", "DOAJ"], outputSchema: schema("LiteratureRetrievalResult", ["records", "providerExecutions", "provenance"]), modelTier: "Deterministic", requiredWorkflowStates: ["Search Plan Approved"], humanReviewRequirement: "Deterministic—researcher review required for disposition", nextStates: ["Retrieval Completed", "Screening"], prohibitedBehavior: [...NEVER, "Create records for provider results not returned"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "screening", purpose: "Propose inclusion/exclusion decisions against approved screening criteria.", allowedInputArtifacts: ["retrievedSources", "approvedScreeningCriteria"], allowedTools: ["structured-language-model"], outputSchema: schema("ScreeningProposal", ["sourceId", "decision", "criterionIds", "rationale"]), modelTier: "Language—Standard", requiredWorkflowStates: ["Retrieval Completed", "Screening Criteria Approved"], humanReviewRequirement: "Required before persistence/use", nextStates: ["Screening Suggested", "Screening Researcher Reviewed"], prohibitedBehavior: [...NEVER, "Exclude a source without criterion-linked researcher review"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: REVIEWERS } }),
  contract({ id: "evidence-extraction", purpose: "Extract source-grounded structured evidence from verified full-text chunks.", allowedInputArtifacts: ["verifiedSource", "fullTextChunks", "extractionQuestion"], allowedTools: ["evidence-extraction-tool"], outputSchema: schema("EvidenceExtractionProposal", ["fields", "sourceChunkIds", "exactPassages"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Source Included", "Full Text Available"], humanReviewRequirement: "Required before downstream use", nextStates: ["Evidence Suggested", "Evidence Researcher Reviewed"], prohibitedBehavior: [...NEVER, "Treat unsupported model text as source evidence"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "literature-synthesis", purpose: "Synthesize only researcher-reviewed evidence records.", allowedInputArtifacts: ["reviewedEvidenceRecords"], allowedTools: ["literature-synthesis-tool"], outputSchema: schema("LiteratureSynthesisProposal", ["themes", "limitations", "unresolvedQuestions", "evidenceIds"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Evidence Researcher Reviewed"], humanReviewRequirement: "Required before downstream use", nextStates: ["Synthesis Suggested", "Synthesis Researcher Reviewed"], prohibitedBehavior: [...NEVER, "Use an unsupported statement as evidence"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "contradiction-detection", purpose: "Propose evidence-linked contradiction groups without adjudicating truth.", allowedInputArtifacts: ["reviewedEvidenceRecords", "reviewedSynthesis"], allowedTools: ["contradiction-analysis-tool"], outputSchema: schema("EvidenceContradictionGroup", ["evidenceIds", "reasons", "uncertainty"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Synthesis Researcher Reviewed"], humanReviewRequirement: "Required before downstream use", nextStates: ["Contradictions Suggested", "Contradictions Researcher Reviewed"], prohibitedBehavior: [...NEVER, "Resolve conflicting evidence without researcher review"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "research-gap", purpose: "Propose research gaps grounded in reviewed synthesis and contradiction records.", allowedInputArtifacts: ["reviewedSynthesis", "reviewedContradictions"], allowedTools: ["research-gap-tool"], outputSchema: schema("ResearchGapProposal", ["gapStatement", "supportingEvidenceIds", "contradictingEvidenceIds", "caution"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Synthesis Researcher Reviewed"], humanReviewRequirement: "Required before downstream use", nextStates: ["Gap Suggested", "Gap Researcher Approved"], prohibitedBehavior: [...NEVER, "Claim novelty from absence of retrieved evidence alone"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "question-hypothesis", purpose: "Propose evidence-linked questions, objectives, and classification-appropriate hypotheses.", allowedInputArtifacts: ["researchCanvas", "confirmedClassification", "reviewedSynthesis", "approvedGap"], allowedTools: ["question-hypothesis-tool"], outputSchema: schema("QuestionHypothesisProposal", ["researchQuestions", "objectives", "hypotheses"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Intake Researcher Confirmed", "Gap Researcher Approved"], humanReviewRequirement: "Required before downstream use", nextStates: ["Questions Suggested", "Questions Researcher Approved"], prohibitedBehavior: [...NEVER, "Force hypotheses for incompatible qualitative or exploratory designs"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "methodology-design", purpose: "Propose classified methodology statements from approved upstream artifacts.", allowedInputArtifacts: ["approvedResearchQuestion", "approvedObjectives", "confirmedClassification", "reviewedEvidence", "approvedGap", "researcherFacts", "confirmedReportingGuidance"], allowedTools: ["methodology-design-tool"], outputSchema: schema("MethodologyDesignProposal", ["sections", "classifications", "sourceIds"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Questions Researcher Approved", "Gap Researcher Approved"], humanReviewRequirement: "Required before downstream use", nextStates: ["Methodology Suggested", "Methodology Researcher Approved"], prohibitedBehavior: [...NEVER, "Invent participants, sample sizes, ethics, instruments, or completed procedures"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "analysis-planning", purpose: "Recommend enabled registered analysis methods without computing.", allowedInputArtifacts: ["approvedMethodology", "datasetProfile", "variableDictionary", "approvedResearchQuestions", "confirmedClassification", "analysisMethodCapabilities"], allowedTools: ["analysis-method-registry", "analysis-planning-tool"], outputSchema: schema("AnalysisPlanningProposal", ["primaryAnalyses", "secondaryAnalyses", "sensitivityAnalyses", "unsupportedNeeds"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Methodology Researcher Approved", "Dataset Profile Available"], humanReviewRequirement: "Required before downstream use", nextStates: ["Analysis Plan Suggested", "Analysis Plan Researcher Approved"], prohibitedBehavior: [...NEVER, "Compute statistics or recommend unregistered/disabled methods"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "results-interpretation-writing", purpose: "Select and order exact approved findings and warnings for deterministic Results writing.", allowedInputArtifacts: ["approvedAnalysisOutputs", "approvedQualitativeFindings", "numericEvidence"], allowedTools: ["numeric-grounding-validator", "results-selection-tool"], outputSchema: schema("ResultsInterpretationProposal", ["sourceResultIds", "findings", "warnings", "manuscriptDraft"]), modelTier: "Language—Standard", requiredWorkflowStates: ["Results Approved for Manuscript"], humanReviewRequirement: "Required before persistence/use", nextStates: ["Results Draft Suggested", "Results Draft Researcher Approved"], prohibitedBehavior: [...NEVER, "Recalculate or alter p-values, sample size, effects, significance, or findings"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "section-writer", purpose: "Propose one evidence-grounded manuscript section.", allowedInputArtifacts: ["sectionRequest", "approvedProjectFacts", "verifiedSources", "approvedAnalysisOutputs"], allowedTools: ["citation-processor", "numeric-grounding-validator", "structured-language-model"], outputSchema: schema("SectionDraftProposal", ["sectionId", "content", "evidenceIds", "missingInformation"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Required Section Inputs Approved"], humanReviewRequirement: "Required before persistence/use", nextStates: ["Section Draft Suggested", "Section Researcher Approved"], prohibitedBehavior: [...NEVER, "Draft Results without approved empirical outputs"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "peer-review", purpose: "Propose reviewer comments against manuscript and approved evidence.", allowedInputArtifacts: ["manuscriptSections", "verifiedSources", "approvedAnalysisOutputs", "reviewerRole"], allowedTools: ["structured-language-model"], outputSchema: schema("PeerReviewProposal", ["comments", "severity", "sectionIds", "suggestedActions"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Manuscript Draft Available"], humanReviewRequirement: "Required before persistence/use", nextStates: ["Review Suggested", "Review Disposed"], prohibitedBehavior: [...NEVER, "Claim human peer review or accept/reject a manuscript"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: REVIEWERS } }),
  contract({ id: "compliance", purpose: "Evaluate deterministic compliance rules against verified requirements.", allowedInputArtifacts: ["manuscript", "verifiedOutletRequirements", "reportingChecklist", "projectGovernance"], allowedTools: ["compliance-engine"], outputSchema: schema("ComplianceReport", ["checks", "blockingIssues", "status"]), modelTier: "Deterministic", requiredWorkflowStates: ["Manuscript Draft Available"], humanReviewRequirement: "Deterministic—researcher review required for disposition", nextStates: ["Compliance Checked"], prohibitedBehavior: [...NEVER, "Treat unverified outlet requirements as binding"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: REVIEWERS } }),
  contract({ id: "integrity-review", purpose: "Evaluate provenance, approval, evidence, and AI-ledger integrity gates.", allowedInputArtifacts: ["projectArtifacts", "auditTrail", "aiLedger", "evidenceGraph"], allowedTools: ["integrity-engine"], outputSchema: schema("IntegrityReview", ["findings", "blockers", "evidenceIds"]), modelTier: "Deterministic", requiredWorkflowStates: ["Project Available"], humanReviewRequirement: "Deterministic—researcher review required for disposition", nextStates: ["Integrity Reviewed"], prohibitedBehavior: [...NEVER, "Infer missing provenance or approval"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: REVIEWERS } }),
  contract({ id: "manuscript-editor", purpose: "Propose bounded edits without changing approved scientific meaning.", allowedInputArtifacts: ["approvedManuscriptSection", "editInstruction", "approvedEvidence"], allowedTools: ["citation-processor", "numeric-grounding-validator", "structured-language-model"], outputSchema: schema("ManuscriptEditProposal", ["sourceSectionId", "proposedContent", "changeSummary"]), modelTier: "Language—Advanced", requiredWorkflowStates: ["Section Researcher Approved"], humanReviewRequirement: "Required before persistence/use", nextStates: ["Edit Suggested", "Edit Researcher Accepted"], prohibitedBehavior: [...NEVER, "Change empirical meaning, citations, or numbers without approved source evidence"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
  contract({ id: "export", purpose: "Create deterministic export artifacts after readiness and integrity gates.", allowedInputArtifacts: ["approvedManuscript", "verifiedReferences", "approvedFigures", "approvedTables", "exportConfiguration"], allowedTools: ["export-engine", "citation-processor"], outputSchema: schema("ExportJobRecord", ["artifactHash", "format", "warnings", "provenance"]), modelTier: "Deterministic", requiredWorkflowStates: ["Submission Ready"], humanReviewRequirement: "Deterministic—researcher review required for disposition", nextStates: ["Export Completed"], prohibitedBehavior: [...NEVER, "Export when readiness, evidence, or integrity gates fail"], permissions: { serverOnly: true, frontendInvocation: "Denied", roles: WRITERS } }),
];

export class AgentRegistry {
  private readonly contracts = new Map<AgentId, AgentContract>();
  constructor(items: readonly AgentContract[]) {
    items.forEach((item) => {
      if (this.contracts.has(item.id)) throw new Error(`Duplicate agent ID '${item.id}'.`);
      if (!item.purpose.trim() || !item.outputSchema.id.trim() || !item.outputSchema.version.trim() || !item.outputSchema.requiredFields.length || !item.requiredWorkflowStates.length || !item.nextStates.length || !item.prohibitedBehavior.length || !item.permissions.roles.length) throw new Error(`Agent '${item.id}' has an incomplete contract.`);
      this.contracts.set(item.id, item);
    });
  }
  get(id: string): AgentContract | undefined { return this.contracts.get(id as AgentId); }
  list(): readonly AgentContract[] { return Object.freeze([...this.contracts.values()]); }
  authorizeFrontend(id: string, role: ProjectRole, suppliedArtifactKeys: readonly string[]): AgentContract {
    const item = this.get(id);
    if (!item) throw new Error(`Agent '${id}' is not registered.`);
    if (item.permissions.frontendInvocation !== "Allowed") throw new Error(`Agent '${id}' cannot be invoked from the frontend.`);
    if (!item.permissions.roles.includes(role)) throw new Error(`Role '${role}' cannot invoke agent '${id}'.`);
    const unsupported = suppliedArtifactKeys.find((key) => !item.allowedInputArtifacts.includes(key));
    if (unsupported) throw new Error(`Input artifact '${unsupported}' is not allowed for agent '${id}'.`);
    return item;
  }
}

export const agentRegistry = new AgentRegistry(definitions);
